name: hdr_utils
description: "A collection of utility functions and extensions for Flutter."
version: 0.0.1
homepage: https://github.com/Harshit2027/hdr_utils
repository: https://github.com/Harshit2027/hdr_utils

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg